export type ToolEntry = {
  name: string;
  kind: "builtin";
  capability: string;
  responsibility: string;
  status: "present";
  source: "compiled";
};

/** Built-in product CLI surface exposed as a tool registry for agents. */
export const BUILTIN_TOOLS: ToolEntry[] = [
  {
    name: "init",
    kind: "builtin",
    capability: "scaffold",
    responsibility: "Install operating files and create DB",
    status: "present",
    source: "compiled",
  },
  {
    name: "migrate",
    kind: "builtin",
    capability: "task-state",
    responsibility: "Legacy: migrate existing harness.db if present",
    status: "present",
    source: "compiled",
  },
  {
    name: "import-sqlite",
    kind: "builtin",
    capability: "task-state",
    responsibility: "Import legacy harness.db into markdown entities",
    status: "present",
    source: "compiled",
  },

  {
    name: "link",
    kind: "builtin",
    capability: "scaffold",
    responsibility: "Register project in global registry",
    status: "present",
    source: "compiled",
  },
  {
    name: "unlink",
    kind: "builtin",
    capability: "scaffold",
    responsibility: "Remove project from global registry",
    status: "present",
    source: "compiled",
  },
  {
    name: "remove",
    kind: "builtin",
    capability: "scaffold",
    responsibility: "Completely delete 5harness from a project",
    status: "present",
    source: "compiled",
  },
  {
    name: "rm",
    kind: "builtin",
    capability: "scaffold",
    responsibility: "Alias for remove — completely delete 5harness from a project",
    status: "present",
    source: "compiled",
  },

  {
    name: "projects",
    kind: "builtin",
    capability: "scaffold",
    responsibility: "List linked projects",
    status: "present",
    source: "compiled",
  },
  {
    name: "project id",
    kind: "builtin",
    capability: "scaffold",
    responsibility: "Read or ensure durable project identity",
    status: "present",
    source: "compiled",
  },
  {
    name: "project role",
    kind: "builtin",
    capability: "scaffold",
    responsibility: "Configure or inspect Project Link role and stack tags",
    status: "present",
    source: "compiled",
  },
  {
    name: "project peer",
    kind: "builtin",
    capability: "scaffold",
    responsibility: "Add, remove, or resolve Project Link peers",
    status: "present",
    source: "compiled",
  },
  {
    name: "dashboard",
    kind: "builtin",
    capability: "scaffold",
    responsibility: "Local multi-project read-only dashboard",
    status: "present",
    source: "compiled",
  },

  {
    name: "intake",
    kind: "builtin",
    capability: "task-specification",
    responsibility: "Classify work before implementation",
    status: "present",
    source: "compiled",
  },
  {
    name: "story add",
    kind: "builtin",
    capability: "task-state",
    responsibility: "Add story matrix row",
    status: "present",
    source: "compiled",
  },
  {
    name: "story update",
    kind: "builtin",
    capability: "task-state",
    responsibility: "Update story status and proof flags",
    status: "present",
    source: "compiled",
  },
  {
    name: "story verify",
    kind: "builtin",
    capability: "verification",
    responsibility: "Run story verify_command",
    status: "present",
    source: "compiled",
  },
  {
    name: "story verify-all",
    kind: "builtin",
    capability: "verification",
    responsibility: "Verify all configured stories",
    status: "present",
    source: "compiled",
  },
  {
    name: "decision add",
    kind: "builtin",
    capability: "project-memory",
    responsibility: "Record durable decision",
    status: "present",
    source: "compiled",
  },
  {
    name: "decision verify",
    kind: "builtin",
    capability: "verification",
    responsibility: "Run decision verify_command",
    status: "present",
    source: "compiled",
  },
  {
    name: "backlog add",
    kind: "builtin",
    capability: "entropy-auditing",
    responsibility: "Add improvement backlog item",
    status: "present",
    source: "compiled",
  },
  {
    name: "backlog close",
    kind: "builtin",
    capability: "entropy-auditing",
    responsibility: "Close backlog item with outcome",
    status: "present",
    source: "compiled",
  },
  {
    name: "trace",
    kind: "builtin",
    capability: "observability",
    responsibility: "Record agent execution trace",
    status: "present",
    source: "compiled",
  },
  {
    name: "score-trace",
    kind: "builtin",
    capability: "observability",
    responsibility: "Score trace quality tiers",
    status: "present",
    source: "compiled",
  },
  {
    name: "audit",
    kind: "builtin",
    capability: "entropy-auditing",
    responsibility: "Drift audit and entropy score",
    status: "present",
    source: "compiled",
  },
  {
    name: "propose",
    kind: "builtin",
    capability: "entropy-auditing",
    responsibility: "Generate proposals from audit findings",
    status: "present",
    source: "compiled",
  },
  {
    name: "query matrix",
    kind: "builtin",
    capability: "task-state",
    responsibility: "Show story proof matrix",
    status: "present",
    source: "compiled",
  },
  {
    name: "query stats",
    kind: "builtin",
    capability: "task-state",
    responsibility: "Show durable counts",
    status: "present",
    source: "compiled",
  },
  {
    name: "query intakes",
    kind: "builtin",
    capability: "task-specification",
    responsibility: "List intakes",
    status: "present",
    source: "compiled",
  },
  {
    name: "query decisions",
    kind: "builtin",
    capability: "project-memory",
    responsibility: "List decisions",
    status: "present",
    source: "compiled",
  },
  {
    name: "query stories",
    kind: "builtin",
    capability: "task-state",
    responsibility: "List stories",
    status: "present",
    source: "compiled",
  },
  {
    name: "query backlog",
    kind: "builtin",
    capability: "entropy-auditing",
    responsibility: "List backlog items",
    status: "present",
    source: "compiled",
  },
  {
    name: "query traces",
    kind: "builtin",
    capability: "observability",
    responsibility: "List traces",
    status: "present",
    source: "compiled",
  },
  {
    name: "query tools",
    kind: "builtin",
    capability: "tool-access",
    responsibility: "List equipped harness tools",
    status: "present",
    source: "compiled",
  },
  {
    name: "reindex",
    kind: "builtin",
    capability: "tool-access",
    responsibility: "Rebuild derived markdown index",
    status: "present",
    source: "compiled",
  },
  {
    name: "get",
    kind: "builtin",
    capability: "tool-access",
    responsibility: "Load one entity by id/path",
    status: "present",
    source: "compiled",
  },
  {
    name: "search",
    kind: "builtin",
    capability: "tool-access",
    responsibility: "Search entities (snippet results)",
    status: "present",
    source: "compiled",
  },
  {
    name: "links",
    kind: "builtin",
    capability: "tool-access",
    responsibility: "Show outbound/backlinks for an entity",
    status: "present",
    source: "compiled",
  },
  {
    name: "docs search",
    kind: "builtin",
    capability: "tool-access",
    responsibility: "Search harness own docs (snippet results)",
    status: "present",
    source: "compiled",
  },
  {
    name: "docs list",
    kind: "builtin",
    capability: "tool-access",
    responsibility: "List all harness docs with titles",
    status: "present",
    source: "compiled",
  },
  {
    name: "docs read",
    kind: "builtin",
    capability: "tool-access",
    responsibility: "Read one harness doc file in full",
    status: "present",
    source: "compiled",
  },
];

export function listTools(filter?: {
  capability?: string;
  status?: string;
}): ToolEntry[] {
  return BUILTIN_TOOLS.filter((t) => {
    if (filter?.capability && t.capability !== filter.capability) return false;
    if (filter?.status && t.status !== filter.status) return false;
    return true;
  });
}
